### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Ympressiv**
Try to work with static mesh colision

### CODE REVIEW

**Comment by ZioYuri78** [comment]
Please don't try to merge the Master branch with the Release branch, i suggest to clone the Master branch and work with it.

**Comment by Ympressiv** [comment]
I'm sorry just now. I have finished writing 3/4 of my thesis and got to the
research stage. Today I will try to comprehend what you wrote! I'm just
downloading the master branch (clones elsewhere)

pt., 18 cze 2021 o 13:49 Yuri Belleri ***@***.***> napisał(a):

**Comment by Ympressiv** [comment]
Ohh you closed this :( I was late. Please open this again. I'm sorry, my bad

sob., 19 cze 2021 o 10:29 Jakub Michalewicz ***@***.***>
napisał(a):

**Comment by Ympressiv** [comment]
ok, it is not working like that, i see now how to clone this, sorry :D My
knowledge about git is still to low

sob., 19 cze 2021 o 10:37 Jakub Michalewicz ***@***.***>
napisał(a):

**Pull request closed without merging**
